// MySql Connection Data

module.exports = {
	USER:'ret_site_users',
	RETFLOAT : 'ret_float',
	TRANSFER : 'ret_transfer',
	USER_LOG_HISTORY : 'ret_user_log_history',
	ADMIN : 'general_setting',
	PAYOUT : 'ret_payout',
	LOTTO_PROFILE : 'lotto_profile',
	FAVOURITE_LOTTO: 'ret_favourite',
	SITE_PROFILE: 'siteprofile',
	SITE_PROFILE_MANAGEMENT : 'siteprofilemanagement',
	SITE_MANAGEMENT : 'sitemanagement',
	LOTTO_LIST : 'lottolist',
	COUNTRY_LIST : 'countrylist',
	LOTTO_EVENT : 'lottoevent',
	RET_MARKET_LIST : 'ret_marketlist',
	PLAYED_EVENT_DETAILS :'played_event_details',
	RET_PLAYED_EVENT_DETAILS :'ret_played_event_details',
	RET_PAYMENT :'ret_payment',
	RET_EVENTS :'ret_events',
	RET_LOTTO_LIST :'ret_lottolists',
	RET_SITE_PROFILE_MANAGEMENT :'ret_siteprofilemanagement',
	RET_SITE_MANAGEMENT :'ret_sitemanagement',
	RET_SITE_PROFILE :'ret_siteprofile',
	RET_AGENT_DEVICES : 'ret_agent_devices',
	RET_DISPLAY_DEVICES : 'ret_display_devices',
	RET_SYNC_AGENT_DISPLAY_DEVICES : 'ret_sync_agent_display_devices',
	RET_SITE_LOGOS : 'ret_sitelogos',
}
